### ISSUE TITLE
Stackrox collector failing after Kubernetes cluster upgrade

### ISSUE THREAD

**Issue by tarakaprabhuchinta** [stackrox/stackrox#6955]
After upgrading Kubernetes cluster from 1.24 to 1.25.6 the collector pods keeps on crashing. 

Here are the details 
1. it is k8s cluster upgrade: 1.24 --> 1.25.6
2. Node OS: Ubuntu 18.04.6 LTS  --> 22.04.2 LTS
3. Node OS Kernel: 5.4.0-1104-azure --> 5.15.0-1040-azure
4. Helm Chart: stackrox-secured-cluster-services 72.0.0
5. Collector: quay.io/stackrox-io/collector-slim:3.72.0
6. Sensor: quay.io/stackrox-io/main:3.72.0

Logs from the sensor:

pkg/kocache: 2023/07/14 23:11:44.069836 source.go:60: Error: probe 2.1.0/collector-ebpf-5.15.0-1040-azure.o.gz does not exist in upstream /kernel-objects
pkg/probeupload: 2023/07/14 23:11:44.069900 server_handler.go:99: Info: kernel probe 2.1.0/collector-ebpf-5.15.0-1040-azure.o.gz not found
common/sensor: 2023/07/14 23:11:44.670593 central_communication_impl.go:163: Info: Communication with central ended.
common/sensor: 2023/07/14 23:11:44.670714 sensor.go:270: Error: Sensor reported an error: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR
main: 2023/07/14 23:11:44.670762 main.go:69: Fatal: Sensor exited with error: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR

Logs from collector:

Collector Version: 3.11.0
OS: Ubuntu 22.04.2 LTS
Kernel Version: 5.15.0-1040-azure

[W 20230712 031837 FileDownloader.cpp:332] Failed to download /module/collector-ebpf.o.gz
[W 20230712 031837 GetKernelObject.cpp:183] Unable to download kernel object collector-ebpf-5.15.0-1040-azure.o to /module/collector-ebpf.o.gz
[W 20230712 031837 collector.cpp:343] Error getting kernel object: collector-ebpf-5.15.0-1040-azure.o
[I 20230712 031837 collector.cpp:215] gRPC server=sensor.stackrox.svc:443
[I 20230712 031837 collector.cpp:357] Attempting to connect to GRPC server
[E 20230712 031837 collector.cpp:359] Unable to connect to the GRPC server.
[F 20230712 031837 collector.cpp:368] No suitable kernel object downloaded

**Comment by Molter73** [comment]
Hi @tarakaprabhuchinta,
I see you are running stackrox 3.72, that version reached EOL some time ago and we are no longer building drivers for newer kernels on it. You will need to update to a newer version of stackrox like 3.74 or 4.0+.

**Comment by tarakaprabhuchinta** [comment]
But the kernel version is already available for the node Im running. (https://github.com/stackrox/collector/blob/bdbd2d30bf6e62b5a296f8171d24fd180a0ba22f/kernel-modules/KERNEL_VERSIONS#L4545). So I dont think its a driver problem

**Comment by Molter73** [comment]
The kernel headers are available in our CI but the driver itself is not built for that version of collector, because it reached EOL, you'll need to update your version of stackrox.
